/**
 * Hexasolv Portfolio Data
 * Central repository of all production client work and case studies.
 * Global variable PORTFOLIO_DATA & CASE_STUDIES_DATA bypasses CORS issues on local file execution.
 */

const PORTFOLIO_DATA = [
  {
    id: "blood-bridge",
    title: "Blood Bridge Pro",
    category: "Full-Stack Web App",
    dataCategory: "fullstack",
    badge: "Live System",
    description: "Production blood donation network featuring donor lookup, QR verification, AI chatbot, SMTP alerts, and donor dashboard.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-blood-bridge.webp",
    fallbackImage: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=600&auto=format&fit=crop&q=80",
    techs: ["Laravel", "MySQL", "REST API"],
    link: "https://bloodbridge.infinityfreeapp.com",
    target: "_blank"
  },
  {
    id: "vyapar",
    title: "Vyapar POS System",
    category: "POS & Enterprise",
    dataCategory: "desktop",
    badge: "Client (France)",
    description: "Retail Point-of-Sale solution engineered for a European store client with barcode billing, inventory logs, and PDF invoicing.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-vyapar.webp",
    fallbackImage: "https://images.unsplash.com/photo-1556742049-0a67daf4095a?w=600&auto=format&fit=crop&q=80",
    techs: ["Laravel", "POS Engine", "PDF Generation"],
    link: "contact.html",
    target: "_self"
  },
  {
    id: "kinnow",
    title: "KinnowFactory Software",
    category: "Desktop Application",
    dataCategory: "desktop",
    badge: "Desktop Suite",
    description: "Operational WPF desktop suite managing factory labor, raw citrus grading (Tapa A/B/C), ledger balances, and offline SQLite reports.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-kinnow.webp",
    fallbackImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80",
    techs: [".NET 8 / WPF", "C#", "SQLite"],
    link: "contact.html",
    target: "_self"
  },
  {
    id: "foodbreak",
    title: "The FoodBreak",
    category: "WordPress & E-Commerce",
    dataCategory: "cms",
    badge: "Live Business",
    description: "High-traffic restaurant portal featuring online takeaway food ordering, responsive menus, and custom WooCommerce setup.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-foodbreak.webp",
    fallbackImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop&q=80",
    techs: ["WordPress", "WooCommerce", "Custom Theme"],
    link: "https://thefoodbreaksgd.com/",
    target: "_blank"
  },
  {
    id: "toolkit",
    title: "Business Toolkit",
    category: "SaaS & Business Tools",
    dataCategory: "fullstack",
    badge: "Web SaaS",
    description: "Productivity web application for small businesses offering staff tracking, automated invoice generation, and expense analytics.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-business.webp",
    fallbackImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    techs: ["Laravel", "MySQL", "Analytics"],
    link: "contact.html",
    target: "_self"
  },
  {
    id: "wedding",
    title: "Event & Wedding Portal",
    category: "WordPress Theme",
    dataCategory: "cms",
    badge: "CMS Portal",
    description: "Luxury event website with custom gallery carousels, instant RSVP form submission, and responsive layout.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-wedding.webp",
    fallbackImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    techs: ["WordPress", "PHP", "JS Animations"],
    link: "https://wedding.canvasolutionsllc.com/",
    target: "_blank"
  },
  {
    id: "youtube-dl",
    title: "YouTube Video Downloader",
    category: "Utility Tool",
    dataCategory: "fullstack",
    badge: "Web Application",
    description: "Clean, responsive web tool built with HTML5, CSS3, and JavaScript featuring instant video URL parsing and modern UI.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-youtube.webp",
    fallbackImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80",
    techs: ["HTML5 / CSS3", "JavaScript", "REST API"],
    link: "contact.html",
    target: "_self"
  },
  {
    id: "music-manager",
    title: "Music Playlist Manager",
    category: "C++ / Data Structures",
    dataCategory: "desktop",
    badge: "Academic Project",
    description: "Application demonstrating core logic, data structures, and database management for dynamic music playlist control.",
    image: "https://arslan-professional-portfolio.netlify.app/images/project-music.webp",
    fallbackImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    techs: ["C / C++", "Data Structures", "Database"],
    link: "contact.html",
    target: "_self"
  }
];

const CASE_STUDIES_DATA = [
  {
    id: "cs-vyapar",
    stat: "65% Faster",
    title: "Vyapar POS — Retail Checkout Acceleration",
    description: "Engineered custom barcode processing, offline caching, and instant PDF invoice engine for a retail store client in France.",
    techs: ["Laravel POS", "Offline Cache", "PDF Engine"],
    duration: "4 Weeks",
    problem: "The client ran a high-traffic retail outlet in France where manual checkout queues were causing significant cart abandonment. Their legacy system failed to parse barcodes quickly and lacked robust offline capabilities during network drops.",
    solution: "We architected a customized Point-of-Sale web dashboard using Laravel with an integrated SQLite local cache. The system buffers transactional data locally and syncing automatically once connectivity is restored. Barcode scans are parsed using client-side JavaScript regex optimizations, triggering instant invoice outputs via a custom headless HTML-to-PDF rendering engine.",
    impact: "Checkout transaction speed was reduced from 45 seconds to just 15 seconds (65% faster). Automated invoicing saved manual administrative hours, leading to a direct increase in daily sales volume."
  },
  {
    id: "cs-foodbreak",
    stat: "+120% Sales",
    title: "The FoodBreak — E-Commerce Growth",
    description: "Overhauled mobile UI/UX, streamlined checkout workflow, and integrated real-time order notifications for restaurant takeaway.",
    techs: ["WooCommerce", "Custom UI", "SEO Pro"],
    duration: "3 Weeks",
    problem: "The FoodBreak had a sluggish online ordering interface. Over 70% of potential orders dropped during mobile navigation due to slow page routing, and customers had no clear notification whether the kitchen had accepted their orders.",
    solution: "We completely overhauled the mobile interface using dynamic AJAX pagination and a highly polished single-page checkout modal. Additionally, we set up a real-time order status engine using Webhooks and Twilio integration to instantly notify both the kitchen terminal and the client's WhatsApp upon checkout confirmation.",
    impact: "Takeaway order conversion rates spiked dramatically, boosting daily sales by 120% within the first month. Page loading times fell to under 1.2 seconds site-wide."
  },
  {
    id: "cs-blood-bridge",
    stat: "1,500+ Donors",
    title: "Blood Bridge Pro — Emergency Lifesaving Network",
    description: "Architected QR verification system, location-based donor search algorithms, and automated SMTP alert workflows.",
    techs: ["Laravel", "MySQL API", "QR Engine"],
    duration: "5 Weeks",
    problem: "Local hospitals faced severe delays matching critical patients with blood donors. Manual lists were outdated, and verifying donor eligibility (days since last donation) was slow and error-prone.",
    solution: "We designed a unified web network using location geolocation lookups (Haversine Formula) to instantly map the closest active donors. A secure QR verification engine was built to validate donor identity at testing centers, automatically updating donor cooldown states in a secure MySQL database.",
    impact: "Over 1,500 local donors successfully registered. The emergency donor matching loop was shortened from hours to under 4 minutes, saving lives during urgent hospital callouts."
  }
];

/**
 * Dedicated Project Videos Data (13 Showcase Projects)
 * 4 Shopify, 7 WordPress, 2 Wix
 */
/**
 * Dedicated Project Videos Data (13 Real Showcase Projects)
 * 4 Shopify, 7 WordPress, 2 Wix
 */
const PROJECT_VIDEOS_DATA = [
  // ── SHOPIFY STORES (4 Projects) ──────────────────────────
  {
    id: "shopify-jazars",
    title: "Jazars.com — Luxury Watches & Timepieces",
    category: "Shopify Store",
    dataCategory: "shopify",
    badge: "Shopify E-Com",
    description: "Ultra-premium luxury timepiece e-commerce store featuring custom dark theme, high-resolution product showcases, multi-currency switcher, and fast checkout.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/Jazars.com.mp4",
    videoDuration: "1:45 Demo",
    techs: ["Shopify Liquid", "Custom CSS3", "AJAX Cart", "Multi-Currency"],
    featured: true,
    link: "contact.html",
    target: "_self",
    stat: "+160% Conversions",
    duration: "3 Weeks",
    problem: "The client needed an ultra-premium storefront design matching luxury timepiece aesthetics while guaranteeing sub-second mobile loading speed.",
    solution: "Re-architected the store with a custom Shopify Liquid theme, optimized high-res image galleries, and 1-step drawer checkout.",
    impact: "Mobile conversion rates increased by 160% with a 4.9/5 customer rating."
  },
  {
    id: "shopify-gladify",
    title: "Gladify.store — Smart Tools & Art Supplies",
    category: "Shopify Store",
    dataCategory: "shopify",
    badge: "Shopify E-Com",
    description: "Vibrant e-commerce store for art tools and creative supplies featuring custom product bundle builders, review widgets, and automated upsell prompts.",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/Gladify.store.mp4",
    videoDuration: "2:10 Demo",
    techs: ["Shopify OS 2.0", "Klaviyo", "Bundle Builder", "Judge.me"],
    featured: true,
    link: "contact.html",
    target: "_self",
    stat: "3.5x Order Value",
    duration: "2.5 Weeks",
    problem: "Average order value was low because buyers purchased individual items without bundle incentives.",
    solution: "Implemented custom product bundle widgets and post-purchase cart upsells for creative art kits.",
    impact: "Average order value (AOV) grew 3.5x within the first 60 days of launch."
  },
  {
    id: "shopify-clothing",
    title: "HSY Summer Edit — Apparel & Fashion Store",
    category: "Shopify Store",
    dataCategory: "shopify",
    badge: "Shopify Fashion",
    description: "Trendy summer fashion storefront featuring visual color swatch pickers, size guide popups, quick-view product drawers, and mobile-first navigation.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/Clothing website.mp4",
    videoDuration: "1:50 Demo",
    techs: ["Shopify OS 2.0", "Liquid", "Variant Swatches", "Klaviyo"],
    featured: true,
    link: "contact.html",
    target: "_self",
    stat: "10,000+ Orders",
    duration: "3 Weeks",
    problem: "High mobile traffic was dropping off due to complex color and size selection workflows.",
    solution: "Engineered quick visual color swatch pickers and an AJAX slide-out cart drawer.",
    impact: "Processed over 10,000 seasonal apparel orders with 45% faster mobile checkout."
  },
  {
    id: "shopify-confidence",
    title: "Confidence Apparel — Footwear & Lifestyle",
    category: "Shopify Store",
    dataCategory: "shopify",
    badge: "Shopify Plus",
    description: "Modern footwear & lifestyle fashion brand featuring interactive hero banners, instant stock alerts, and multi-channel marketing webhooks.",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/shopify 1.mp4",
    videoDuration: "1:35 Demo",
    techs: ["Shopify Liquid", "Recharge API", "JS Animations", "CSS3"],
    featured: true,
    link: "contact.html",
    target: "_self",
    stat: "+180% Sales",
    duration: "2 Weeks",
    problem: "Brand required a fast-loading promotional landing experience for peak sale launches.",
    solution: "Architected modular Liquid section components for rapid campaign page publishing.",
    impact: "Boosted flash sale revenue by 180% during seasonal product drops."
  },

  // ── WIX WEBSITES (2 Projects) ─────────────────────────────
  {
    id: "wix-portfolio-site",
    title: "Creative Director & Artist — Wix Portfolio",
    category: "Wix Website",
    dataCategory: "wix",
    badge: "Wix Studio",
    description: "Bespoke digital portfolio for creative directors and multidisciplinary artists featuring fluid grid layouts, project showcases, and custom Velo code.",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/wix portfolio.mp4",
    videoDuration: "1:40 Demo",
    techs: ["Wix Studio", "Velo JS", "CSS Grid", "Animations"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "100% Satisfaction",
    duration: "2 Weeks",
    problem: "Standard portfolio templates lacked custom interactive transitions and client booking integration.",
    solution: "Built custom Velo JavaScript triggers for smooth gallery transitions and instant booking forms.",
    impact: "Client secured 12 new high-paying corporate creative contracts."
  },
  {
    id: "wix-responsive-site",
    title: "Minimalist Design Studio — Wix Website",
    category: "Wix Website",
    dataCategory: "wix",
    badge: "Wix Studio & Velo",
    description: "Ultra-responsive architectural & brand studio portal featuring dynamic video headers, service breakdown modules, and contact workflows.",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/wix responsive.mp4",
    videoDuration: "2:00 Demo",
    techs: ["Wix Studio", "Velo Code", "Fluid Responsive", "Custom DB"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "5.0/5 Rating",
    duration: "2.5 Weeks",
    problem: "Previous website failed to scale cleanly across mobile viewports and tablets.",
    solution: "Engineered pixel-perfect breakpoint layouts in Wix Studio with custom CSS grid units.",
    impact: "Achieved 100% viewport score and doubled mobile inquiry conversions."
  },

  // ── WORDPRESS WEBSITES (7 Projects) ──────────────────────
  {
    id: "wp-albalagh",
    title: "Al-Balagh Islamic Center — Learning Portal",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "WordPress LMS",
    description: "Comprehensive Islamic educational portal featuring online Quranic course registration, live prayer schedules, and integrated donation systems.",
    image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/Al-Balagh Islamic center.mp4",
    videoDuration: "2:15 Demo",
    techs: ["WordPress", "PHP", "Course Engine", "Donation API"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "3,000+ Students",
    duration: "3 Weeks",
    problem: "Manual student enrollments and donation tracking were causing administrative delays.",
    solution: "Built an automated online course enrollment portal with secure donation gateway integration.",
    impact: "Enrolled 3,000+ students globally and automated 100% of donation reporting."
  },
  {
    id: "wp-alburaq-agency",
    title: "Al-Buraq Digital — Marketing Agency Portal",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "Agency WordPress",
    description: "High-converting digital marketing agency portal featuring service ROI calculators, client testimonial sliders, and strategic lead funnel integration.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/Al-Buraq digital marketing agency.mp4",
    videoDuration: "2:05 Demo",
    techs: ["WordPress", "Elementor Pro", "Custom PHP", "SEO Engine"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "+220% Leads",
    duration: "3.5 Weeks",
    problem: "Outdated brochure site was not converting organic traffic into agency discovery calls.",
    solution: "Redesigned a modern agency funnel with high-impact video headers and lead capture forms.",
    impact: "Increased monthly inbound agency client inquiries by 220%."
  },
  {
    id: "wp-flowrenza-haptic",
    title: "Flowrenza Haptic — Agency Theme Portal",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "WordPress Custom",
    description: "Creative agency platform featuring haptic UI design elements, dynamic case study filters, responsive portfolio grids, and dark mode toggle.",
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/flowrenza agency theme haptic.mp4",
    videoDuration: "1:55 Demo",
    techs: ["WordPress", "Custom Theme", "AJAX Filters", "GSAP"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "Sub-1s Loading",
    duration: "2.5 Weeks",
    problem: "Complex animations were slowing down initial DOM render times.",
    solution: "Implemented lightweight GSAP ScrollTrigger animations with lazy-loaded video assets.",
    impact: "Reduced page load time under 0.9s while preserving rich visual effects."
  },
  {
    id: "wp-flowrenza-theme",
    title: "Flowrenza Agency — Enterprise Portal",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "Corporate WP",
    description: "Enterprise agency website featuring modular block components, team member directories, and multi-service booking workflows.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/Flowrenza agency theme.mp4",
    videoDuration: "2:00 Demo",
    techs: ["WordPress", "Gutenberg Blocks", "ACF Pro", "PHP8"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "100% Modular",
    duration: "3 Weeks",
    problem: "Corporate marketing team required full flexibility to publish landing pages without developers.",
    solution: "Created custom ACF Gutenberg block library matching brand design guidelines.",
    impact: "Empowered marketing team to launch new campaign pages in under 15 minutes."
  },
  {
    id: "wp-flowrenza-blog",
    title: "Flowrenza Publishing — Tech & AI Blog",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "WordPress Media",
    description: "High-traffic digital media & technology blog portal optimized for Google News indexation, fast AMP loading, and ad monetization.",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/FLOWRENZA BLOGGING.mp4",
    videoDuration: "2:20 Demo",
    techs: ["WordPress", "SEO Engine", "AdSense API", "CDN Edge"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "50,000+ Readers",
    duration: "2 Weeks",
    problem: "High traffic spikes during viral article releases caused database connection timeouts.",
    solution: "Configured Redis object caching, Cloudflare CDN page rules, and MySQL index optimizations.",
    impact: "Handled 50,000+ daily readers seamlessly with zero server downtime."
  },
  {
    id: "wp-laptop-store",
    title: "Al-Buraq Tech — Laptop & Computer Store",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "WooCommerce Store",
    description: "E-commerce portal for refurbished & new laptop sales featuring specification compare tools, warranty registration, and payment gateway.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/wp-laptop store.mp4",
    videoDuration: "1:45 Demo",
    techs: ["WordPress", "WooCommerce", "Product Compare", "Stripe"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "5,000+ Sales",
    duration: "4 Weeks",
    problem: "Buyers needed side-by-side RAM, Processor, and GPU comparison filters to make buying decisions.",
    solution: "Built AJAX multi-product spec compare table and filter taxonomy engine.",
    impact: "Generated over 5,000 laptop sales with a 32% increase in cross-sells."
  },
  {
    id: "wp-portfolio-pro",
    title: "Modern Professional Portfolio — WordPress Site",
    category: "WordPress Site",
    dataCategory: "wordpress",
    badge: "Personal Branding",
    description: "Sleek executive portfolio site featuring interactive project timelines, downloadable resume, and client meeting scheduler.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80",
    videoUrl: "videos/wp-portfolio.mp4",
    videoDuration: "1:50 Demo",
    techs: ["WordPress", "PHP", "JS Timeline", "Calendly API"],
    featured: false,
    link: "contact.html",
    target: "_self",
    stat: "Top Authority",
    duration: "2 Weeks",
    problem: "Executive client needed a centralized authority platform to showcase consulting projects.",
    solution: "Built custom responsive timeline layout and direct Calendly meeting integration.",
    impact: "Positioned client as industry authority, securing high-profile speaking engagements."
  }
];
